KCRM.Web/Controllers/Reports/PurchaseReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KCRM.Logic;
using KCRM.Logic.Reports;
using KCRM.Model.DbModels.Tables.Enums;
using KCRM.Model.Models;
using KCRM.Model.Models.Reports;

namespace KCRM.Web.Controllers.Reports
{
    public class PurchaseReportController : KcrmReportController
    {
        private readonly PurchaseReportLogic _logic;
        private const string TempModel = "PurchaseReportModel";

        public PurchaseReportController()
            : this(new PurchaseReportLogic())
        {
        }

        public PurchaseReportController(PurchaseReportLogic logic)
            : base(PermissionEmun.PurchaseReport)
        {
            _logic = logic;
        }

        private PurchaseReportModel GetTempData()
        {
            PurchaseReportModel model = (TempData[TempModel] == null)
                ? new PurchaseReportModel()
                : (PurchaseReportModel)TempData[TempModel];
            return model;
        }

        private ICollection<PurchaseModel> GetSearchResult(PurchaseReportModel model)
        {
            return _logic.GetSearchResult(model.SupplierId, model.CustomerId, model.UserId, model.FromDate, model.ToDate);
        }

        public ActionResult Index()
        {
            return View("Search");
        }

        public ActionResult Search()
        {
            return View();
        }
        
        #region GetAll

        [HttpGet]
        public JsonResult GetCustomers(long id)
        {
            return Json(_logic.GetCustomersBySupplierId(id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetUsers(long customerId, long supplierId)
        {
            return Json(_logic.GetPurchaserByCustomerAndSupplier(customerId, supplierId), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetSuppliers()
        {
            return Json(_logic.GetSuppliers(), JsonRequestBehavior.AllowGet);
        }
        #endregion

        [HttpPost]
        public JsonResult SearchResult(long supplierId, long customerId, long userId, DateTime fromDate, DateTime toDate)
        {
            var model = new PurchaseReportModel()
            {
                SupplierId = supplierId,
                CustomerId = customerId,
                UserId = userId,
                FromDate = fromDate,
                ToDate = toDate
            };
            return Json(GetSearchResult(model), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SetTempModel(long supplierId, long customerId, long userId, DateTime fromDate, DateTime toDate, DateTime reportDate)
        {
            var model = new PurchaseReportModel()
            {
                SupplierId = supplierId,
                CustomerId = customerId,
                UserId = userId,
                FromDate = fromDate,
                ToDate = toDate,
                ReportDate = reportDate
            };
            TempData[TempModel] = model;
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PurchasePdf()
        {
            var model = GetTempData();
            model.Purchases = GetSearchResult(model);
            return ViewPdf("", "PurchaseList",model);
        }
        public ActionResult Purchase()
        {
            var model = GetTempData();
            model.Purchases = GetSearchResult(model);
            return View("PurchaseList", model);
        }
    }
}

KCRM.Web/Views/PurchaseReport/PurchaseList.cshtml
@using System.Web.UI.HtmlControls
@using iTextSharp.text.html.simpleparser
@using KCRM.Model.DbModels.Tables
@using KCRM.Model.Models
@model KCRM.Model.Models.Reports.PurchaseReportModel

@{
    ViewBag.Title = "Purchase Report";
}

<style>
    table {
        border: 1px solid black;
        border-collapse: collapse;
        width: 685px;
    }

    thead {
        font-size: 10px;
        font-weight: bold;
    }

    tbody {
        font-size: 10px;
        font-weight: normal;
    }

    td {
        border: 1px solid black;
        border-style: solid;
        border-color: black;
        text-align: center;
        padding: 10px;
    }

    th {
        border: 1px solid black;
        border-style: solid;
        border-color: black;
        text-align: center;
        padding: 10px;
    }

    h2, h4, h6 {
        margin: 0px;
        padding: 0px;
    }

    #header {
        width: 100%;
        height: auto;
        text-align: center;
        position: relative;
        font-family: "Times New Roman", Arial, serif;
    }
</style>

<div>
    <div id="header">
        <h2>Stock Admin Co. Name</h2>
        <h4>Purchase Quotation Report</h4>
        <h6>Date of creation : <span>@Model.ReportDate.ToString("MMMM dd, yyyy")</span></h6>
    </div> 
</div>

<div>
    <br/>
    <table>
        <thead>
            <tr>
                <th>Sl</th>
                <th>Date of Purchase</th>
                <th>Supplier</th>
                <th>Customer</th>
                <th>Purchaser</th>
                <th>Product Name</th>
                <th>Unit</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            @{ int count = 0; int rowspan = 1;}}
            @foreach (PurchaseModel aValue in Model.Purchases)
            {
                rowspan = 1;
                count++;
                rowspan += aValue.Products.Count();
                <tr>
                    <td rowspan="@(rowspan)">@count</td>
                    <td rowspan="@(rowspan)">@aValue.DateOfCreation.ToShortDateString()</td>
                    <td rowspan="@(rowspan)">@aValue.Supplier</td>
                    <td rowspan="@(rowspan)">@aValue.Customer</td>
                    <td rowspan="@(rowspan)">@aValue.Purchaser</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td rowspan="@(rowspan)">@aValue.Products.Sum(x => x.Price)</td>
                </tr>
                foreach (ProductModel aProduct in aValue.Products)
                {
                    <tr>
                        <td>@aProduct.Name</td>
                        <td>@aProduct.UnitName</td>
                        <td>@aProduct.Quantity</td>
                        <td>@aProduct.Price</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

KCRM.Web/Views/PurchaseReport/Search.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Purchase Report";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#">Reports</a>
    <a class="current" href="#">Purchase Report</a>
}


<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-pencil"></i> </span>
                <h5>Report Filters</h5>
            </div>
            <div class="widget-content">
                <form action="#" class="form-horizontal">
                <div class="row-fluid">
                    <div class="span6 ">
                        <div class="control-group">
                            <label class="control-label">From Date</label>
                            <div class="controls">
                                <input type="text" readonly="readonly" data-date-format="dd-mm-yyyy" class="datepicker span12" data-bind="datepicker: fromDate">
                                <span class="help-block">(dd-mm-yyyy)</span>
                            </div>
                        </div>
                    </div>   
                </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">To Date</label>
                                <div class="controls">
                                    <input type="text" readonly="readonly" data-date-format="dd-mm-yyyy" class="datepicker span12" data-bind="datepicker: toDate">
                                    <span class="help-block">(dd-mm-yyyy)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                <div class="row-fluid">
                    <div class="span6 ">
                        <div class="control-group">
                            <label class="control-label">
                                Supplier
                            </label>
                            <div class="controls">
                                <select class="span12" data-bind="options: suppliers,
                                                                    optionsText: 'name',
                                                                    optionsValue: 'id',
                                                                    optionsCaption: '--- All ---',
                                                                    value: supplierId"></select>
                            </div>
                        </div>
                    </div> 
                </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Customer
                                </label>
                                <div class="controls">
                                    <select class="span12" data-bind="options: customers,
                                                                    optionsText: 'name',
                                                                    optionsValue: 'id',
                                                                    optionsCaption: '--- All ---',
                                                                    value: customerId"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Purchaser
                                </label>
                                <div class="controls">
                                    <select class="span12" data-bind="options: users,
                                                                    optionsText: 'loginName',
                                                                    optionsValue: 'id',
                                                                    optionsCaption: '--- All ---',
                                                                    value: userId"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid" style="margin: 10px">
                        <div class="span6">
                            <button class="btn btn-success" type="button" data-bind="click: search"><i class="icon-search"></i>&nbsp;Search to show</button>
                        </div>
                    </div>
                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon"> <i class="icon-pencil"></i> </span>
                            <h5>Purchase Details</h5>
                        </div>
                        <div class="widget-content nopadding">
                            <table class="table table-bordered data-table">
                                <thead>
                                    <tr>
                                        <th style="font-size: small">Date of Purchase</th>
                                        <th style="font-size: small">Supplier</th>
                                        <th style="font-size: small">Customer</th>
                                        <th style="font-size: small">Purchaser</th>
                                        <th style="font-size: small">Product Name</th>
                                        <th style="font-size: small">Unit</th>
                                        <th style="font-size: small">Quantity</th>
                                        <th style="font-size: small">Price</th>
                                        <th style="font-size: small">Total Price</th>
                                    </tr>
                                </thead>
                                <tbody data-bind="foreach: searches">
                                    <tr>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: dateOfCreation, attr: { rowspan: products.length + 1 }"></td>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: supplierName, attr: { rowspan: products.length + 1 }"></td>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: customerName, attr: { rowspan: products.length + 1 }"></td>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: purchaserName, attr: { rowspan: products.length + 1 }"></td>
                                        <td style="border: 0px; padding: 0px"></td>  
                                        <td style="border: 0px; padding: 0px"></td>  
                                        <td style="border: 0px; padding: 0px"></td>  
                                        <td style="border: 0px; padding: 0px"></td>  
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: totalPrice(), attr: { rowspan: products.length + 1 }"></td>      
                                    </tr>  
                                    <!-- ko foreach: products -->
                                    <tr>                           
                                        <td style="text-align: center" data-bind="text: name"></td>
                                        <td style="text-align: center" data-bind="text: unit"></td>
                                        <td style="text-align: center" data-bind="text: quantity"></td>
                                        <td style="text-align: center" data-bind="text: price"></td>                      
                                    </tr>
                                    <!-- /ko -->
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="form-actions">                    
                        @*<a class="btn btn-primary" href="@Url.Action("PurchasePdf", "PurchaseReport")" target="_blank"><i class="icon-copy"></i>&nbsp;&nbsp;Generate Report</a>&nbsp;&nbsp;*@
                        <a class="btn btn-primary" data-bind="click: setTempModel">
                            <i class="icon-copy"></i>&nbsp;Generate Report
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/Reports/PurchaseReport/Search.js")"></script>
}