KCRM.Web/Controllers/ProductUnitManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KCRM.Logic;
using KCRM.Model.DbModels.Tables;
using KCRM.Model.DbModels.Tables.Enums;
using KCRM.Model.Models;

namespace KCRM.Web.Controllers
{
    public class ProductUnitManageController : KcrmController
    {
        private readonly ProductUnitManageLogic _logic;

        public ProductUnitManageController()
            : this(new ProductUnitManageLogic())
        {
            
        }
        public ProductUnitManageController(ProductUnitManageLogic productUnitManageLogic) : base(PermissionEmun.ProductSetup)
        {
            _logic = productUnitManageLogic;
        }     

        #region GetAll

        public ActionResult Index()
        {
            return View("All");
        }

        public ActionResult All()
        {
            return View();
        }

        public JsonResult Get(long id)
        {
            return Json(_logic.Get(id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAll()
        {
            return Json(_logic.GetAll(), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Create

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult IsNameUsed(string name)
        {
            return Json(_logic.NameUsed(name), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(ProductUnit productUnit)
        {
            productUnit.AddedByUserId = GetUserSessionModel().Id;
            productUnit.AddedDateTime = DateTime.Now;
            return Json(_logic.TryToAdd(productUnit), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Update

        [HttpGet]
        public ActionResult Update(long id)
        {
            return View(id);
        }

        [HttpPost]
        public JsonResult IsNameUsedExceptProductUnit(string name, long id)
        {
            return Json(_logic.NameUsedExceptProductUnit(name, id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(ProductUnit productUnit)
        {
            productUnit.ReplacedByUserId = GetUserSessionModel().Id;
            productUnit.ReplacedDateTime = DateTime.Now;
            return Json(_logic.TryToReplace(productUnit), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Delete

        [HttpPost]
        public JsonResult Delete(long id)
        {
            ProductUnit productUnit = new ProductUnit()
            {
                Id = id,
                ReplacedByUserId = GetUserSessionModel().Id,
                ReplacedDateTime = DateTime.Now
            };
            _logic.Remove(productUnit);
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

KCRM.Web/Views/ProductUnitManage/All.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Product Unit List";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="current" href="#">Product Unit Setup</a>
    <a class="current" href="#">Product Unit List</a>
}


<div class="row-fluid">
    <div class="row-fluid" style="margin: 10px">
        <div class="span6">
            <a class="btn btn-success" href="@Url.Action("Create", "ProductUnitManage")">
                <i class="icon-plus"></i> Create
            </a>
        </div>
    </div>
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon"><i class="icon-th"></i></span>
            <h5>All Product Units</h5>
        </div>

        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th style="font-size: small">Name</th>
                        <th style="font-size: small">Description</th>
                        <th style="font-size: small">Action</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: productUnits">
                    <tr>
                        <td style="text-align: center" data-bind="text: name"></td>
                        <td style="text-align: center" data-bind="text: description"></td>
                        <td style="text-align: center">
                            <a data-bind="attr: { href: updateUrl }">
                                Update
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/ProductUnitManage/All.js")"></script>
}

KCRM.Web/Views/ProductUnitManage/Create.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Create Product Unit";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="current" href="#">Product Unit Setup</a>
    <a class="current" href="#">Create Product Unit</a>
}
@section goBackLink
{
    <p>
        <a class="btn btn-info" href="@Url.Action("All", "ProductUnitManage")">
            <i class="m-icon-big-swapleft m-icon-white"></i>
        </a>
    </p>
}

<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Product Unit Info</h5>
            </div>
            <div class="widget-content">
                <form id="form-wizard" class="form-horizontal" method="post">
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">
                                Name
                                <span style="font-weight: bold; color: red">*</span>
                            </label>
                            <div class="controls">
                                <input data-bind="value:name" class="span5" type="text" name="name" placeholder="type unit name" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Description</label>
                            <div class="controls">
                                <div class="input-icon left">
                                    <textarea data-bind="value:description" class="span5" placeholder="give some description"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button class="btn btn-success" type="button" data-bind="click:save">Create</button> &nbsp;
                        <button class="btn btn-primary" type="button" data-bind="click:clear">Reset</button>
                    </div>
                    <div id="submitted"></div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/ProductUnitManage/Create.js")"></script>
}

KCRM.Web/Views/ProductUnitManage/Update.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Update Product Unit";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="current" href="#">Product Unit Setup</a>
    <a class="current" href="#">Update Product Unit</a>
}
@section goBackLink
{
    <p>
        <a class="btn btn-info" href="@Url.Action("All", "ProductUnitManage")">
            <i class="m-icon-big-swapleft m-icon-white"></i>
        </a>
    </p>
}

<div class="row-fluid">

    <input type="hidden" value="@(Model)" id="txtProductUnitId" />

    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-align-justify"></i> </span>
                <h5>Personal Info</h5>
            </div>
            <div class="widget-content">
                <form id="form-wizard" class="form-horizontal" method="post">
                    <div id="form-wizard-1" class="step">
                        <div class="control-group">
                            <label class="control-label">
                                Name
                                <span style="font-weight: bold; color: red">*</span>
                            </label>
                            <div class="controls">
                                <input data-bind="value:name" class="span5" id="name" type="text" name="name" placeholder="type your name" />
                            </div>
                        </div>
                        <div class="control-group">
                            <label class="control-label">Description</label>
                            <div class="controls">
                                <div class="input-icon left">
                                    <textarea data-bind="value:description" class="span5" placeholder="give some description"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button class="btn btn-success" type="button" data-bind="click: update">Update</button> &nbsp;
                        <button class="btn btn-primary" type="button" data-bind="click: reset">Reset</button>
                    </div>
                    <div id="submitted"></div>
                </form>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/ProductUnitManage/Update.js")"></script>
}