KCRM.Web/Controllers/Reports/SalesReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KCRM.Logic.Reports;
using KCRM.Model.DbModels.Tables;
using KCRM.Model.DbModels.Tables.Enums;
using KCRM.Model.DbModels.Views;
using KCRM.Model.Models;
using KCRM.Model.Models.Reports;

namespace KCRM.Web.Controllers.Reports
{
    public class SalesReportController : KcrmReportController
    {
        private readonly SalesReportLogic _logic;
        private const string TempModel = "SalesReportModel";

        public SalesReportController()
            : this(new SalesReportLogic())
        {

        }
        public SalesReportController(SalesReportLogic logic)
            : base(PermissionEmun.SalesReport)
        {
            _logic = logic;
        }

        private SalesReportModel GetTempData()
        {
            SalesReportModel model = (TempData[TempModel] == null)
                ? new SalesReportModel()
                : (SalesReportModel)TempData[TempModel];
            return model;
        }

        private ICollection<SaleModel> GetAllSales(SalesReportModel model)
        {

            return _logic.GetSales(model.FromDate, model.ToDate, model.CustomerId);
        }


        #region Views
        public ActionResult Index()
        {
            return View("Search");
        }

        public ActionResult Search()
        {
            return View();
        }

        public ActionResult SalesPdf()
        {
            var model = GetTempData();
            model.Sales = GetAllSales(model);
            return ViewPdf("", "Sales", model);
        }
        public ActionResult Sales()
        {
            var model = GetTempData();
            model.Sales = GetAllSales(model);
            return View(model);
        }
        #endregion

        #region Get
        [HttpGet]
        public JsonResult GetCustomers()
        {
            return Json(_logic.GetCustomer(), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetSales(DateTime fromDate, DateTime toDate, long customerId)
        {
            var model = new SalesReportModel()
            {
                FromDate = fromDate,
                ToDate = toDate,
                CustomerId = customerId
            };
            return Json(GetAllSales(model), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SetTempModel(DateTime fromDate, DateTime toDate, DateTime reportDate, long customerId)
        {
            var model = new SalesReportModel()
            {
                FromDate = fromDate,
                ToDate = toDate,
                ReportDate = reportDate,
                CustomerId = customerId
            };
            TempData[TempModel] = model;
            return Json(true, JsonRequestBehavior.AllowGet);
        }
        #endregion

    }
}

KCRM.Web/Views/SalesReport/Sales.cshtml
@using KCRM.Model.Models;
@model KCRM.Model.Models.Reports.SalesReportModel

@{
    ViewBag.Title = "Sales Report";
}

<style>
    table {
        border: 1px solid black;
        border-collapse: collapse;
        width: 685px;
    }

    thead {
        font-size: 10px;
        font-weight: bold;
    }

    tbody {
        font-size: 10px;
        font-weight: normal;
    }

    td {
        border: 1px solid black;
        border-style: solid;
        border-color: black;
        text-align: center;
        padding: 10px;
    }

    th {
        border: 1px solid black;
        border-style: solid;
        border-color: black;
        text-align: center;
        padding: 10px;
    }

    h2, h4, h6 {
        margin: 0px;
        padding: 0px;
    }

    #header {
        width: 100%;
        height: auto;
        text-align: center;
        position: relative;
        font-family: "Times New Roman", Arial, serif;
    }
</style>

<div id="header">
    <h2>Stock Admin Co. Name</h2>
    <h4>Sales Report</h4>
    <h6>Date of creation : <span>@Model.ReportDate.ToString("MMMM dd, yyyy")</span></h6>
</div>

<div>
    <br/>
    <table style="border: 1px solid black; border-collapse: collapse; width: 685px">
        <thead style="font-size: 10px; font-weight: bold">
            <tr>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">SI</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Date of Sales</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Customer Name</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Product Name</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Unit</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Quantity</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Stock Quntity</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Price</th>
                <th style="border: 1px solid black; text-align: center; padding: 10px;">Total Price</th>
            </tr>
        </thead>
        <tbody style="font-size: 10px; font-weight: normal">
            @{int count = 0; int rowspan = 1;}
            @foreach (SaleModel aModel in Model.Sales)
            {
                ++count;
                rowspan = 1;
                rowspan += aModel.SoldProducts.Count;
                <tr>
                    <td rowspan="@(rowspan)" style="border: 1px solid black; text-align: center; padding: 10px;">@count</td>
                    <td rowspan="@(rowspan)" style="border: 1px solid black; text-align: center; padding: 10px;">@aModel.DateOfCreation.ToString("dd/MM/yyyy")</td>
                    <td rowspan="@(rowspan)" style="border: 1px solid black; text-align: center; padding: 10px;">@aModel.Customer.Name</td>
                    <td style="border: 1px solid black; text-align: center; padding: 10px;"></td>
                    <td style="border: 1px solid black; text-align: center; padding: 10px;"></td>
                    <td style="border: 1px solid black; text-align: center; padding: 10px;"></td>
                    <td style="border: 1px solid black; text-align: center; padding: 10px;"></td>
                    <td style="border: 1px solid black; text-align: center; padding: 10px;"></td>
                    <td rowspan="@(rowspan)" style="border: 1px solid black; text-align: center; padding: 10px;">@aModel.SoldProducts.Sum(x => x.Price)</td>
                </tr>

                foreach (SoldProductModel aSoldProduct in aModel.SoldProducts)
                {
                    long stocktConsumption = (aSoldProduct.HasStockConsumption) ? aSoldProduct.StockConsumptions.ToList()[0].Quantity : 0;
                    <tr>
                        <td style="border: 1px solid black; text-align: center; padding: 10px;">@aSoldProduct.Product.Name</td>
                        <td style="border: 1px solid black; text-align: center; padding: 10px;">@aSoldProduct.Product.UnitName</td>
                        <td style="border: 1px solid black; text-align: center; padding: 10px;">@aSoldProduct.Quantity</td>
                        <td style="border: 1px solid black; text-align: center; padding: 10px;">@stocktConsumption</td>
                        <td style="border: 1px solid black; text-align: center; padding: 10px;">@aSoldProduct.Price</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

KCRM.Web/Views/SalesReport/Search.cshtml
@model dynamic

@{
    ViewBag.PageHeader = ViewBag.Title = "Sales Report";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Report</a>
    <a class="tip-bottom" href="#">Sales</a>
}

<div class="row-fluid">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-pencil"></i> </span>
                <h5>Sales info.</h5>
            </div>
            <div class="widget-content">
                <form action="#" class="form-horizontal">
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">From Date</label>
                                <div class="controls">
                                    <input type="text" readonly="readonly" data-date-format="dd-mm-yyyy" class="datepicker span12" data-bind="datepicker: fromDate">
                                    <span class="help-block">(dd-mm-yyyy)</span>
                                </div>
                            </div>
                        </div>    
                        </div>
                <!--/span-->
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">To Date</label>
                                <div class="controls">
                                    <input type="text" readonly="readonly" data-date-format="dd-mm-yyyy" class="datepicker span12" data-bind="datepicker: toDate">
                                    <span class="help-block">(dd-mm-yyyy)</span>
                                </div>
                            </div>
                        </div>
                        <!--/span-->
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Customer Name
                                </label>
                                <div class="controls">
                                    <select class="span12" data-bind="options: customers,
                                                                        optionsText: 'name',
                                                                        optionsValue: 'id',
                                                                        optionsCaption: '--- All ---',
                                                                        value: customerId"></select>
                                </div>
                            </div>
                        </div>
                        <!--/span-->                   
                    </div>
                    <div class="row-fluid" style="margin: 10px">
                        <div class="span6">
                            <a class="btn btn-success" data-bind="click: getSales">
                                <i class="icon-search"></i> Search to show
                            </a>
                        </div>
                    </div>
                    <div class="widget-box">
                        <div class="widget-title">
                            <span class="icon"> <i class="icon-pencil"></i> </span>
                            <h5>Sales List</h5>
                        </div>
                        <div class="widget-content nopadding">
                            <table class="table table-bordered data-table">
                                <thead>
                                    <tr>
                                        <th style="font-size: small">Date of Sales</th>
                                        <th style="font-size: small">Customer Name</th>
                                        <th style="font-size: small">Product Name</th>
                                        <th style="font-size: small">Unit</th>
                                        <th style="font-size: small">Quantity</th>
                                        <th style="font-size: small">Stock Cons Quntity</th>
                                        <th style="font-size: small">Price</th>
                                        <th style="font-size: small">Total Price</th>
                                    </tr>
                                </thead>
                                <tbody data-bind="foreach: sales">
                                    <tr>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: dateOfCreation, attr: { rowspan: products().length + 1 }"></td>
                                        <td style="text-align: center; vertical-align: middle" data-bind="text: customerName, attr: { rowspan: products().length + 1}"></td>
                                        <td style="border: 0px; padding: 0px"></td>
                                        <td style="border: 0px; padding: 0px"></td>
                                        <td style="border: 0px; padding: 0px"></td>
                                        <td style="border: 0px; padding: 0px"></td>
                                        <td style="border: 0px; padding: 0px"></td>
                                        <td style="text-align: center" data-bind="text: totalPrice(), attr: { rowspan: products().length + 1 }"></td>
                                    </tr>
                                    <!-- ko foreach: products() -->
                                    <tr>
                                        <td style="text-align: center" data-bind="text: name"></td>
                                        <td style="text-align: center" data-bind="text: unitName"></td>
                                        <td style="text-align: center" data-bind="text: quantity"></td>
                                        <td style="text-align: center" data-bind="text: stockQuantity"></td>
                                        <td style="text-align: center" data-bind="text: price"></td>
                                    </tr>
                                    <!-- /ko -->
                                </tbody>
                            </table>
                        </div>
                    </div>


                    <div class="form-actions">
                        @*<a class="btn btn-primary" href="@Url.Action("SalesPdf", "SalesReport")" target="_blank">
                            <i class="icon-copy"></i>&nbsp;Generate Report
                        </a>*@
                        <a class="btn btn-primary" data-bind="click: setTempModel">
                            <i class="icon-copy"></i>&nbsp;Generate Report
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/Reports/SalesReport/Search.js")"></script>
}