KCRM.Web/Controllers/ProductManageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using KCRM.Logic;
using KCRM.Model.DbModels.Tables;
using KCRM.Model.DbModels.Tables.Enums;
using KCRM.Model.DbModels.Tables.Mimics;
using KCRM.Model.Models;

namespace KCRM.Web.Controllers
{
    public class ProductManageController : KcrmController
    {
        private readonly ProductManageLogic _logic;

        public ProductManageController()
            : this(new ProductManageLogic())
        {
            
        }
        public ProductManageController(ProductManageLogic productManageLogic) :base(PermissionEmun.ProductSetup)
        {
            _logic = productManageLogic;
        }   

        #region Get

        public ActionResult Index()
        {
            return View("All");
        }

        public ActionResult All()
        {
            return View();
        }

        public JsonResult Get(long id)
        {
            return Json(_logic.Get(id), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetAll()
        {
            return Json(_logic.GetAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductCategories()
        {
            return Json(_logic.GetProductCategories(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductUnits()
        {
            return Json(_logic.GetProductUnits(), JsonRequestBehavior.AllowGet);
        }
        #endregion
        
        #region Create

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public JsonResult IsNameUsed(string name)
        {
            return Json(_logic.NameUsed(name), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Create(Product product)
        {   
            product.AddedByUserId = GetUserSessionModel().Id;
            product.AddedDateTime = DateTime.Now;
            return Json(_logic.TryToAdd(product), JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Update

        public ActionResult Update(long id)
        {
            return View(id);
        }

        [HttpPost]
        public JsonResult IsNameUsedExceptProduct(string name, long id)
        {
            return Json(_logic.NameUsedExceptProduct(name, id), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult Update(Product product)
        {
            product.ReplacedByUserId = GetUserSessionModel().Id;
            product.ReplacedDateTime = DateTime.Now;
            return Json(_logic.TryToReplace(product), JsonRequestBehavior.AllowGet);
        }
        #endregion   
    }
}

KCRM.Web/Views/ProductManage/All.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Product List";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="current" href="#">Product Setup</a>
    <a class="current" href="#">Product List</a>
}


<div class="row-fluid">
    <div class="row-fluid" style="margin: 10px">
        <div class="span6">
            <a class="btn btn-success" href="@Url.Action("Create", "ProductManage")">
                <i class="icon-plus"></i> Create
            </a>
        </div>
    </div>
    <div class="widget-box">
        <div class="widget-title">
            <span class="icon"><i class="icon-th"></i></span>
            <h5>All Products</h5>
        </div>

        <div class="widget-content nopadding">
            <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th style="font-size: small">Product Name</th>
                        <th style="font-size: small">Product Category</th>
                        <th style="font-size: small">Product Unit</th>
                        <th style="font-size: small">Date of Creation</th>
                        <th style="font-size: small">Description</th>
                        <th style="font-size: small">Action</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: products">
                    <tr>
                        <td style="text-align: center" data-bind="text: name"></td>
                        <td style="text-align: center" data-bind="text: category"></td>
                        <td style="text-align: center" data-bind="text: unitType"></td>
                        <td style="text-align: center" data-bind="text: dateOfCreation"></td>
                        <td style="text-align: center" data-bind="text: description"></td>
                        <td style="text-align: center">
                            <a data-bind="attr: { href: updateUrl }">
                                Update
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/ProductManage/All.js")"></script>
}

KCRM.Web/Views/ProductManage/Create.cshtml
@{
    ViewBag.PageHeader = ViewBag.Title = "Create Product";
} 

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="current" href="#">Product Setup</a>
    <a class="current" href="#">Create Product</a>
} 
@section goBackLink
{
    <p>
        <a class="btn btn-info" href="@Url.Action("All", "ProductManage")">
            <i class="m-icon-big-swapleft m-icon-white"></i>
        </a>
    </p>
}
@*pop up for product unit create*@
<div id="divProductUnitSetup" class="modal hide fade modal-wide75" tabindex="-1" data-focus-on="input:first">
    <div class="modal-header">
        <a id="btnClose1" class="btn btn-success pull-right" data-dismiss="modal" aria-hidden="false">×</a>
        <div class="widget-title noborder">
            <span class="icon"><i class="icon-th"></i></span>
            <h5>Create Product Unit</h5>
        </div>
    </div>
    <div class="modal-body nopadding nomargin">
        <div class="widget-box nomargin">
            <div class="widget-content">
                <form action="#" class="form-horizontal" data-bind="template: { name: 'productUnitCreate', data: productUnitCreate }"></form>
            </div>
        </div>
    </div>
</div>

<div id="divProductSetup" class="row-fluid" tabindex="-1" data-focus-on="input:first">
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-pencil"></i> </span>
                <h5>Product Info</h5>
            </div>
            <div class="widget-content">
                <form action="#" class="form-horizontal">
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Name
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <input data-bind="value:name" class="span12" type="text" name="name" placeholder="type product name" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Category
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <select id="sltProductCategory" class="span12" data-bind="value: productCategory"></select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Unit
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <select id="sltUnit" class="span12" data-bind="value: unit">  </select>
                                </div>
                            </div>
                        </div>
                        @*add + sign for add option*@
                        <div class="span6">
                            <div class="control-group">
                                <div class="controls" style="margin-left: 0">
                                    <a id="btnAddProductUnit" class="btn btn-success" data-toggle="modal">
                                        <i class="icon-plus">&nbsp;</i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">Description</label>
                                <div class="controls">
                                    <textarea class="span12" draggable="false" data-bind="value:description" placeholder="give some description"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Date of creation
                                </label>
                                <div class="controls">
                                    <input data-bind="datepicker: dateOfCreation" class="datepicker span12" type="text" readonly="readonly" data-date-format="dd-mm-yyyy">
                                    <span class="help-block">(dd-mm-yyyy)</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-actions">
                        <button class="btn btn-success" type="button" data-bind="click:create">Create</button>
                        <button class="btn btn-primary" type="button" data-bind="click:reset">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section scripts
{    
    <script src="@Url.Content("~/Scripts/Views/Shared/Vms/Vm.productUnit.create.js")"></script>
    <script src="@Url.Content("~/Scripts/Views/ProductManage/Create.js")"></script>  
}

KCRM.Web/Views/ProductManage/Update.cshtml
@model long

@{
    ViewBag.PageHeader = ViewBag.Title = "Update Product";
}

@section breadcrumbs
{
    <a class="tip-bottom" href="#" data-original-title="">Setups</a>
    <a class="tip-bottom" href="#">Product Setup</a>
    <a class="current" href="#">Update Product</a>
} 
@section goBackLink
{
    <p>
        <a class="btn btn-info" href="@Url.Action("All", "ProductManage")">
            <i class="m-icon-big-swapleft m-icon-white"></i>
        </a>
    </p>
}


<div class="row-fluid">
    <input type="hidden" value="@(Model)" id="txtProductId" />
    <div class="span12">
        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"> <i class="icon-pencil"></i> </span>
                <h5>Product Info</h5>
            </div>
            <div class="widget-content">
                <form action="#" class="form-horizontal">
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Name
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <input data-bind="value:name" class="span12" type="text" name="name" />
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Category
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <select id="sltProductCategory" class="span12" data-bind="value: category" />
                                </div>
                            </div>
                        </div>
                        <div class="span6 ">
                            <div class="control-group">                               
                                <div class="controls">
                                    <input type="text" class="span4"style="display: none"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Product Unit
                                    <span style="font-weight: bold; color: red">*</span>
                                </label>
                                <div class="controls">
                                    <input id="sltUnit" type="text" data-bind="value:unitType" class="span12" readonly=" "/>
                                </div>
                            </div>
                        </div>    
                    </div>
                    
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">Description</label>
                                <div class="controls">
                                    <textarea class="span12" draggable="false" data-bind="value:description"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span6 ">
                            <div class="control-group">
                                <label class="control-label">
                                    Date of creation
                                </label>
                                <div class="controls">
                                    <input data-bind="datepicker:dateOfCreation" class="datepicker span12" type="text" data-date-format="dd-mm-yyyy" placeholder="select date">
                                    <span class="help-block">Date with Formate of (dd-mm-yyyy)</span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <button class="btn btn-success" type="button" data-bind="click:update">Update</button>
                        <button class="btn btn-primary" type="button" data-bind="click:reset">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>




@section scripts
{
    <script src="@Url.Content("~/Scripts/Views/ProductManage/Update.js")"></script>
}